language: python
dist: trusty
php:
  - "7.2"
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - composer global require psy/psysh:@stable
  - pip install .
script:
  - make test
  - python -m psysh_kernel install --user
