language: python
python:
  - "3.5"
install:
  - sudo apt-get update -qq;
  - pip install ipykernel jupyter_client traitlets jupyter_kernel_test flit
  - flit install
  - python -m psysh_kernel.install
script:
  - python test_psysh_kernel.py
